run:
  tests: true
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  # additional linters that aren't enabled by default
  enable:
    # - asciicheck
    # - cyclop
    # - dogsled
    # - dupl
    - errcheck
    - errorlint
    # - exhaustive
    # - forbidigo
    # - funlen
    - goconst
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nestif
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0.0
    skip-tests: false

  dogsled:
    max-blank-identifiers: 2

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt:.*
      - io/ioutil:^Read.*

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false

  forbidigo:
    forbid:
      - ^print.*$
    exclude-godoc-examples: false

  funlen:
    lines: 60
    statements: 40
    ignore-comments: true

  goconst:
    min-len: 3
    min-occurrences: 3

  godot:
    scope: declarations
    capital: false

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/geoffjay/agent

  gosec:
    excludes:
      - G104 # Audit errors not checked
    confidence: medium
    severity: medium

  nestif:
    min-complexity: 4

  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers, sayRepetitiveInsteadOfStutters]
